# -*- coding: utf-8 -*-
"""back propogation(FRAUD&KEROS).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ya4B5g0OECFdT0vHeiwIdUaG6707brkH
"""

import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

# -----------------------------
# Simulated transaction data
# -----------------------------
# Each row = one transaction
# Columns could represent: amount, time, merchant risk, frequency, etc.
num_features = 10

X_train = np.random.rand(2000, num_features)
y_train = np.random.randint(0, 2, size=(2000,))  # 0 = normal, 1 = fraud

X_test = np.random.rand(400, num_features)
y_test = np.random.randint(0, 2, size=(400,))

# -----------------------------
# Feed-forward neural network
# -----------------------------
model = Sequential([
    Dense(64, activation='relu', input_shape=(num_features,)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')  # Binary classification
])

# -----------------------------
# Compile the model
# -----------------------------
model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# -----------------------------
# Train the model
# -----------------------------
model.fit(
    X_train,
    y_train,
    epochs=25,
    batch_size=32,
    validation_split=0.2
)

# -----------------------------
# Evaluate the model
# -----------------------------
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)

# -----------------------------
# Predict fraud probability
# -----------------------------
fraud_probabilities = model.predict(X_test)
print("Sample fraud probabilities:", fraud_probabilities[:5])