# -*- coding: utf-8 -*-
"""Brain tumor NNDL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CTGbSfXfOR23xEhLkx4zYuXDGkWMcqYf
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("masoudnickparvar/brain-tumor-mri-dataset")

print("Path to dataset files:", path)

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2
import random

from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import confusion_matrix, classification_report

train_path = "/kaggle/input/brain-tumor-mri-dataset/Training"
test_path = "/kaggle/input/brain-tumor-mri-dataset/Testing"

classes = os.listdir(train_path)
print('Classes: ', classes)

data_info = []
for cls in classes:
    train_count = len(os.listdir(os.path.join(train_path, cls)))
    test_count = len(os.listdir(os.path.join(test_path, cls)))

    data_info.append([cls, train_count, test_count])

df = pd.DataFrame(data_info, columns=["Class", "Train Count", "Test Count"])
print(df)

plt.figure(figsize=(11, 9))
for i, cls in enumerate(classes):
    img_path = os.path.join(train_path, cls, random.choice(os.listdir(os.path.join(train_path, cls))))
    img = cv2.imread(img_path, 0)

    plt.subplot(2, 2, i+1)
    plt.imshow(img, 'gray')
    plt.title(cls)
    plt.axis('off')

plt.tight_layout()
plt.show()