# -*- coding: utf-8 -*-
"""feed forward network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aqqlkPdA9hHfsNuc-VE1LCKwznF3acSD
"""

import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

i = np.array([[1, 2, 3]])

w = np.array([[0.1, 0.2],
              [0.3, 0.4],
              [0.5, 0.6]])

b = np.array([0.1, 0.2])

z = np.dot(i, w) + b

output = sigmoid(z)

print("Output:", output)
a= sigmoid(z)
print("Activated output:",a)
w2=np.array([[0.1,0.2,0.3],[0.4,0.5,0.6]])
b2=np.array([0.1,0.2,0.3])
z2=np.dot(a,w2)+b2
output2=sigmoid(z2)
print("Output2:",output2)

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

X = np.array([[2.0, 3.0, 4.0]])
y = np.array([[0.5, 0.8]])
model = Sequential([
    Dense(4, input_dim=3, activation='sigmoid'),
    Dense(2, activation='sigmoid')
])

model.compile(
    optimizer=tf.keras.optimizers.SGD(learning_rate=0.1),
    loss='mean_squared_error'
)

model.fit(X, y, epochs=1000, verbose=0)

output = model.predict(X)
print("Final output after training:", output)

import numpy as np

class FeedForwardNeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size, lr=0.1):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.lr = lr

        self.W1 = np.random.randn(input_size, hidden_size) * 0.1
        self.b1 = np.zeros(hidden_size)
        self.W2 = np.random.randn(hidden_size, output_size) * 0.1
        self.b2 = np.zeros(output_size)

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

    def forward(self, X):
        self.z1 = np.dot(X, self.W1) + self.b1
        self.a1 = self.sigmoid(self.z1)

        self.z2 = np.dot(self.a1, self.W2) + self.b2
        self.a2 = self.sigmoid(self.z2)
        return self.a2

    def backward(self, X, y, output):
        error = y - output
        delta2 = error * self.sigmoid_derivative(output)

        delta1 = delta2.dot(self.W2.T) * self.sigmoid_derivative(self.a1)

        self.W2 += self.a1.T.dot(delta2) * self.lr
        self.b2 += np.sum(delta2, axis=0) * self.lr

        self.W1 += X.T.dot(delta1) * self.lr
        self.b1 += np.sum(delta1, axis=0) * self.lr

    def train(self, X, y, epochs=1000):
        for epoch in range(epochs):
            output = self.forward(X)
            self.backward(X, y, output)
            if (epoch+1) % 100 == 0:
                loss = np.mean((y - output) ** 2)
                print(f"Epoch {epoch+1}, Loss: {loss:.4f}")

if __name__ == "__main__":
    X = np.array([[1, 2, 3]])

    y = np.array([[0, 1]])

    nn = FeedForwardNeuralNetwork(input_size=3, hidden_size=4, output_size=2, lr=0.1)

    nn.train(X, y, epochs=1000)

    output = nn.forward(X)
    print("Final output after training:", output)

import torch
import torch.nn as nn
import torch.optim as optim

class FeedForwardNeuralNetwork(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(FeedForwardNeuralNetwork, self).__init__()
        self.hidden = nn.Linear(input_size, hidden_size)
        self.output = nn.Linear(hidden_size, output_size)
        self.sigmoid = nn.Sigmoid()
    def forward(self, x):
        x = self.sigmoid(self.hidden(x))
        x = self.output(x)
        return x

if __name__ == "__main__":
    X = torch.tensor([[2.0, 3.0, 4.0]])
    y = torch.tensor([[2.0, 3.0]])

    model = FeedForwardNeuralNetwork(input_size=3, hidden_size=4, output_size=2)

    criterion = nn.MSELoss()
    optimizer = optim.SGD(model.parameters(), lr=0.1)

    epochs = 1000
    for epoch in range(epochs):
        optimizer.zero_grad()
        output = model(X)
        loss = criterion(output, y)
        loss.backward()
        optimizer.step()

        if (epoch+1) % 100 == 0:
            print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

    output = model(X)
    print("Final output after training:", output.detach().numpy())