# -*- coding: utf-8 -*-
"""Twodigits.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UkAskMLL-lTr69Wcl3crTFI_10j5NPTe
"""

# -----------------------------
# Visualize ONE example of EACH digit
# -----------------------------
fig, axes = plt.subplots(1, 2, figsize=(8, 4))

shown = {0: False, 1: False}

for i in range(len(x_test)):
    image = x_test[i]
    label = y_test[i]

    prediction = model.predict(image[np.newaxis, ...], verbose=0)
    pred_class = np.argmax(prediction)

    # Show one sample per digit
    if not shown[label]:
        predicted_digit = digit_a if pred_class == 0 else digit_b
        true_digit = digit_a if label == 0 else digit_b

        axes[label].imshow(image.squeeze(), cmap='gray')
        axes[label].set_title(
            f"True: {true_digit}\nPred: {predicted_digit}\n"
            f"P({digit_a})={prediction[0][0]:.2f}, "
            f"P({digit_b})={prediction[0][1]:.2f}"
        )
        axes[label].axis('off')

        shown[label] = True

    if all(shown.values()):
        break

plt.tight_layout()
plt.show()